### ISSUE TITLE
Баги бекэнда моделей

### ISSUE THREAD

**Issue by GTFB** [GTFB/Altrp3#188]
- [ ] не добавились при создании модели soft_deletes time_stamps в миграцию
![изображение](https://user-images.githubusercontent.com/23271651/89577020-bd110980-d838-11ea-9778-4e5e0f98490a.png)
![изображение](https://user-images.githubusercontent.com/23271651/89577035-c5694480-d838-11ea-80b6-9fd54d7ff774.png)
но трейты добавляются
![изображение](https://user-images.githubusercontent.com/23271651/89578750-54775c00-d83b-11ea-8084-7b9a5aaa1e1e.png)
, поэтому возникает ошибка
![изображение](https://user-images.githubusercontent.com/23271651/89578840-7a9cfc00-d83b-11ea-9534-7281feaf4c90.png)

- [x] не добавился индекс для колонки
![изображение](https://user-images.githubusercontent.com/23271651/89577275-1da04680-d839-11ea-8711-fa113ec09e11.png)
![изображение](https://user-images.githubusercontent.com/23271651/89577313-2e50bc80-d839-11ea-87c2-a2f7a1b6478c.png)

- [ ] при добавлении связи многие поля в БД обнулились и везде поставилось restrict хотя я ставил cascade
![изображение](https://user-images.githubusercontent.com/23271651/89580365-dc5e6580-d83d-11ea-8652-6a23210707fc.png)

**Comment by GTFB** [comment]
- [x] Если у поля отмечено Editable, то это поле должно добавляться в массив $fillable, но этого не происходит 
![изображение](https://user-images.githubusercontent.com/23271651/89628894-a1901800-d8a5-11ea-9ffe-9d15cdb5a5b2.png)
![изображение](https://user-images.githubusercontent.com/23271651/89628997-c2f10400-d8a5-11ea-8267-3cdd84b4ec0f.png)

**Comment by GTFB** [comment]
- [ ] не смог удалить модель
запрос
Request URL: http://altrp.nz/admin/ajax/models/13
Request Method: DELETE
ошибка:
```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function delete() on null in file G:\local\altrp.nz\app\Observers\AltrpModelObserver.php on line 194

#0 [internal function]: App\Observers\AltrpModelObserver->deleting(Object(App\Altrp\Model))
#1 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(388): call_user_func_array(Array, Array)
#2 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(218): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.deleti...', Array)
#3 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(191): Illuminate\Events\Dispatcher->dispatch('eloquent.deleti...', Array, true)
#4 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasEvents.php(189): Illuminate\Events\Dispatcher->until('eloquent.deleti...', Object(App\Altrp\Model))
#5 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(905): Illuminate\Database\Eloquent\Model->fireModelEvent('deleting')
#6 G:\local\altrp.nz\app\Http\Controllers\Admin\ModelsController.php(313): Illuminate\Database\Eloquent\Model->delete()
#7 [internal function]: App\Http\Controllers\Admin\ModelsController->destroyModel('13')
#8 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#9 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('destroyModel', Array)
#10 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Admin\ModelsController), 'destroyModel')
#11 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController()
#12 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Route->run()
#13 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#32 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 G:\local\altrp.nz\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 G:\local\altrp.nz\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#48 G:\local\altrp.nz\public\main.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#49 G:\local\altrp.nz\public\index.php(32): require('G:\\local\\altrp....')
#50 {main}
```

**Comment by GTFB** [comment]
- [ ] не смог добавить связь
![изображение](https://user-images.githubusercontent.com/23271651/89650017-6227f280-d8ca-11ea-937e-7510413aca64.png)
```
{
    "message": "Trying to get property 'altrp_table' of non-object",
    "exception": "ErrorException",
    "file": "G:\\local\\altrp.nz\\app\\Altrp\\Generators\\Migration\\MigrationKey.php",
    "line": 116,
    "trace": [
        {
            "file": "G:\\local\\altrp.nz\\app\\Altrp\\Generators\\Migration\\MigrationKey.php",
            "line": 116,
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\app\\Altrp\\Generators\\Migration\\MigrationKey.php",
            "line": 70,
            "function": "setText",
            "class": "App\\Altrp\\Generators\\Migration\\MigrationKey",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\app\\Altrp\\Generators\\Migration\\MigrationKey.php",
            "line": 53,
            "function": "create",
            "class": "App\\Altrp\\Generators\\Migration\\MigrationKey",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\app\\Altrp\\Generators\\KeyMigrationGenerator.php",
            "line": 24,
            "function": "up",
            "class": "App\\Altrp\\Generators\\Migration\\MigrationKey",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\app\\Observers\\AltrpRelationshipObserver.php",
            "line": 27,
            "function": "createKeyGenerate",
            "class": "App\\Altrp\\Generators\\KeyMigrationGenerator",
            "type": "->"
        },
        {
            "function": "creating",
            "class": "App\\Observers\\AltrpRelationshipObserver",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php",
            "line": 388,
            "function": "call_user_func_array"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php",
            "line": 218,
            "function": "Illuminate\\Events\\{closure}",
            "class": "Illuminate\\Events\\Dispatcher",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Events\\Dispatcher.php",
            "line": 191,
            "function": "dispatch",
            "class": "Illuminate\\Events\\Dispatcher",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasEvents.php",
            "line": 189,
            "function": "until",
            "class": "Illuminate\\Events\\Dispatcher",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php",
            "line": 795,
            "function": "fireModelEvent",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php",
            "line": 675,
            "function": "performInsert",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\app\\Http\\Controllers\\Admin\\ModelsController.php",
            "line": 555,
            "function": "save",
            "class": "Illuminate\\Database\\Eloquent\\Model",
            "type": "->"
        },
        {
            "function": "storeModelRelation",
            "class": "App\\Http\\Controllers\\Admin\\ModelsController",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php",
            "line": 54,
            "function": "call_user_func_array"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php",
            "line": 45,
            "function": "callAction",
            "class": "Illuminate\\Routing\\Controller",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 219,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\ControllerDispatcher",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php",
            "line": 176,
            "function": "runController",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 681,
            "function": "run",
            "class": "Illuminate\\Routing\\Route",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 130,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php",
            "line": 41,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\SubstituteBindings",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php",
            "line": 43,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Auth\\Middleware\\Authenticate",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php",
            "line": 76,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php",
            "line": 49,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\View\\Middleware\\ShareErrorsFromSession",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php",
            "line": 56,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Session\\Middleware\\StartSession",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php",
            "line": 37,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php",
            "line": 66,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Cookie\\Middleware\\EncryptCookies",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 105,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 683,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 658,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 624,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php",
            "line": 613,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 170,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 130,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php",
            "line": 63,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\fideloper\\proxy\\src\\TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 171,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php",
            "line": 105,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 145,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php",
            "line": 110,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\public\\main.php",
            "line": 55,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "G:\\local\\altrp.nz\\public\\index.php",
            "line": 32,
            "function": "require"
        }
    ]
}
```
тело запроса
```
{"title":"Relation to Inner","description":"","type":"hasOne","model_id":"15","add_belong_to":false,"local_key":"id","foreign_key":"relation_to_inner","onDelete":"cascade","onUpdate":"cascade","name":"relation_to_inner","target_model_id":"16"}
```
