### ISSUE TITLE
crop image bugs

### ISSUE THREAD

**Issue by talp-525** [GTFB/Altrp3#674]
- [x] Take the file name from the file itself

- [x] tiff type doesn't work (remove from list)

- [x] when the upload method is called, an exception is thrown and the request is not sent

- [x] the aspect ratio of the sides is violated if the height and width of the widget are set (visible if the width of the loaded image is greater than the height)
- [x] delete all console.log

**Comment by talp-525** [comment]
- [x] exception when call method `upload` on empty widget:
```
TypeError: Cannot read properties of undefined (reading 'data')
    at _callee6$ (InputCropImageWidget.js:539)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at InputCropImageWidget.upload (asyncToGenerator.js:21)
    at AltrpAction._callee25$ (AltrpAction.js:1149)
```

**Comment by talp-525** [comment]
- [x] delete this
![изображение](https://user-images.githubusercontent.com/54500710/147744114-1817bf07-1a6e-4f1a-9ace-45870d114f1a.png)
crop sizes should has this settings 
![изображение](https://user-images.githubusercontent.com/54500710/147744179-79ee5f05-b355-40ad-a1e9-86541860046f.png)
croping image align by center

**Comment by talp-525** [comment]
- [x] selected image shouldn`t overflow container
![изображение](https://user-images.githubusercontent.com/54500710/147744345-569045d3-a1b2-4f4a-9722-fd8c9744dd0c.png)

- [x] media request only when call method `upload` not user selectable new image
- [x] when the user just selected an image it should be selected like this:
![изображение](https://user-images.githubusercontent.com/54500710/147745410-4481d8d8-ee1f-4e2b-b078-6d8a12430f73.png)

**Comment by talp-525** [comment]
- [x] exception when call `selectOther` on empty widget
 ```
react_devtools_backend.js:4045 TypeError: Cannot read properties of null (reading 'click')
    at _callee5$ (InputCropImageWidget.js:533)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at InputCropImageWidget.selectOther (asyncToGenerator.js:21)
    at AltrpAction._callee25$ (AltrpAction.js:1148)
```
- [x] exception after select other image

```
Uncaught TypeError: Cannot read properties of null (reading 'height')
    at InputCropImageWidget.render (InputCropImageWidget.js:604)
    at finishClassComponent (react-dom.development.js:17485)
    at updateClassComponent (react-dom.development.js:17435)
    at beginWork (react-dom.development.js:19073)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
    at workLoopSync (react-dom.development.js:22707)
render @ InputCropImageWidget.js:604
finishClassComponent @ react-dom.development.js:17485
updateClassComponent @ react-dom.development.js:17435
beginWork @ react-dom.development.js:19073
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(анонимная) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
flushPendingDiscreteUpdates @ react-dom.development.js:22372
flushDiscreteUpdates @ react-dom.development.js:22353
finishEventHandler @ react-dom.development.js:3714
batchedEventUpdates @ react-dom.development.js:3748
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
react_devtools_backend.js:4045 The above error occurred in the <InputCropImageWidget> component:

    at InputCropImageWidget (http://localhost:3001/src/InputCropImageWidget.b3658f3efaf2fdf637ea.bundle.js:319:83)
    at SimpleElementWrapper (http://localhost:3001/src/SimpleElementWrapper.081f1103abdc9c03b0bc.bundle.js:169:83)
    at ConnectFunction (http://localhost:3001/src/bundle.h-altrp.js:55064:68)
    at Provider (http://localhost:3001/src/bundle.h-altrp.js:54778:20)

React will try to recreate this component tree from scratch using the error boundary you provided, SimpleElementWrapper.
overrideMethod @ react_devtools_backend.js:4045
logCapturedError @ react-dom.development.js:20085
callback @ react-dom.development.js:20154
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20709
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(анонимная) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
flushPendingDiscreteUpdates @ react-dom.development.js:22372
flushDiscreteUpdates @ react-dom.development.js:22353
finishEventHandler @ react-dom.development.js:3714
batchedEventUpdates @ react-dom.development.js:3748
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
Показать ещё 2 фрейма
react_devtools_backend.js:4045 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at InputCropImageWidget (http://localhost:3001/src/InputCropImageWidget.b3658f3efaf2fdf637ea.bundle.js:319:83)
```
